# Generated by Django 6.0 on 2025-12-04 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, help_text='Adresse postale affichée dans la colonne de gauche.', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.CharField(blank=True, help_text='Disponibilités : temps, type de missions, délai, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='useful_info',
            field=models.TextField(blank=True, help_text='Infos utiles : permis, véhicule, mobilité, remote, etc.'),
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Ex: Esprit entrepreneurial, Habitué au remote, ...', max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='cv.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: Français, Anglais, Allemand, ...', max_length=100)),
                ('level', models.CharField(blank=True, help_text='Ex: Langue maternelle, Courant (C1), Technique...', max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv.profile')),
            ],
        ),
    ]
